import type { OfferCategory, OfferUnit } from "./offer-input";

export type PilotProduct = {
  id: string;
  brand: string;
  name: string;
  category: OfferCategory;
  defaultVolume: number;
  unit: OfferUnit;
  segment: string;
  comparisonMode: "same_product" | "unit_value";
  sourceTargets: readonly string[];
};

export const pilotRequiredSourcesPerChannel = 2;

export const pilotProducts: readonly PilotProduct[] = [
  {
    // 4대 온라인 면세점 취급 확인(2026-08-15): 롯데·신라·현대 상품 페이지
    // 검증, 신세계는 브라우저로 확인(봇 차단). 면세 표기는 "밤 B5"(트래블
    // 리테일 SKU), 국내는 "밤 B5+" — 같은 라인의 세대 차이로 보이며 등록
    // 시 용량·구성으로 대조한다.
    id: "lrp-cicaplast-balm-b5",
    brand: "라로슈포제",
    name: "시카플라스트 밤 B5",
    category: "cosmetics",
    defaultVolume: 100,
    unit: "ml",
    segment: "더모코스메틱 진정 밤",
    comparisonMode: "same_product",
    sourceTargets: ["롯데·신라·신세계·현대", "라로슈포제 공식몰·쿠팡"],
  },
  {
    // 면세는 50ml(점보)·50ml×2만 취급, 국내 본품은 30ml. 같은 상품의
    // 용량 차이이므로 단위가로 비교한다 (ANR 100/50과 같은 패턴).
    id: "lrp-hyalu-b5-serum",
    brand: "라로슈포제",
    name: "히알루 B5 세럼",
    category: "cosmetics",
    defaultVolume: 30,
    unit: "ml",
    segment: "더모코스메틱 세럼",
    comparisonMode: "same_product",
    sourceTargets: ["롯데·신라·신세계·현대", "라로슈포제 공식몰·쿠팡"],
  },
  {
    // 신라 단독 확인(2026-08-15): /p/4777651 라이브 검증, 세일가 $9.1
    // (12,875원), 바코드 8809695360527. 다른 3사는 미취급이지만 면세
    // 출처는 한 곳이면 비교가 성립한다. 공유 픽의 "약산성 클렌징 젤 폼
    // 200ml"과는 같은 브랜드의 다른 상품 — 그쪽 파트너 링크를 이 항목에
    // 이어붙이지 않는다.
    id: "drg-red-blemish-soothing-foam",
    brand: "닥터지",
    name: "약산성 레드 블레미쉬 클리어 수딩 폼",
    category: "cosmetics",
    defaultVolume: 150,
    unit: "ml",
    segment: "더모코스메틱 클렌징 폼",
    comparisonMode: "same_product",
    sourceTargets: ["신라", "올리브영·이랜드몰·쿠팡"],
  },
  {
    id: "estee-lauder-anr",
    brand: "에스티 로더",
    name: "어드밴스드 나이트 리페어",
    category: "cosmetics",
    defaultVolume: 50,
    unit: "ml",
    segment: "럭셔리 세럼",
    comparisonMode: "same_product",
    sourceTargets: ["롯데·신라·신세계·현대", "쿠팡·국내몰"],
  },
  {
    id: "sk-ii-facial-treatment-essence",
    brand: "SK-II",
    name: "페이셜 트리트먼트 에센스",
    category: "cosmetics",
    defaultVolume: 160,
    unit: "ml",
    segment: "럭셔리 에센스",
    comparisonMode: "same_product",
    sourceTargets: ["롯데·신라·신세계·현대", "쿠팡·국내몰"],
  },
  {
    id: "sulwhasoo-concentrated-ginseng-cream",
    brand: "설화수",
    name: "자음생크림 클래식",
    category: "cosmetics",
    defaultVolume: 50,
    unit: "ml",
    segment: "럭셔리 크림",
    comparisonMode: "same_product",
    sourceTargets: ["롯데·신라·신세계·현대", "국내 공식몰"],
  },
  {
    id: "anua-heartleaf-pore-control-cleansing-oil",
    brand: "아누아",
    name: "어성초 포어 컨트롤 클렌징오일",
    category: "cosmetics",
    defaultVolume: 200,
    unit: "ml",
    segment: "K-뷰티 클렌징",
    comparisonMode: "same_product",
    sourceTargets: ["롯데·신라·신세계·현대", "올리브영·쿠팡"],
  },
  {
    id: "anua-heartleaf-quercetinol-cleansing-foam",
    brand: "아누아",
    name: "어성초 쿼세티놀 모공 딥 클렌징 폼",
    category: "cosmetics",
    defaultVolume: 150,
    unit: "ml",
    segment: "K-뷰티 클렌징",
    comparisonMode: "same_product",
    sourceTargets: ["롯데·신라·신세계·현대", "올리브영·쿠팡"],
  },
  {
    id: "torriden-dive-in-serum",
    brand: "토리든",
    name: "다이브인 저분자 히알루론산 세럼",
    category: "cosmetics",
    defaultVolume: 50,
    unit: "ml",
    segment: "K-뷰티 세럼",
    comparisonMode: "unit_value",
    sourceTargets: ["롯데·신라·신세계·현대", "올리브영·쿠팡"],
  },
  {
    id: "round-lab-birch-juice-sunscreen",
    brand: "라운드랩",
    name: "자작나무 수분 선크림",
    category: "cosmetics",
    defaultVolume: 50,
    unit: "ml",
    segment: "K-뷰티 선케어",
    comparisonMode: "unit_value",
    sourceTargets: ["롯데·신라·신세계·현대", "올리브영·쿠팡"],
  },
  {
    id: "beauty-of-joseon-relief-sun",
    brand: "조선미녀",
    name: "맑은쌀 선크림",
    category: "cosmetics",
    defaultVolume: 50,
    unit: "ml",
    segment: "K-뷰티 선케어",
    comparisonMode: "unit_value",
    sourceTargets: ["롯데·신라·신세계·현대", "올리브영·쿠팡"],
  },
  {
    id: "aestura-atobarrier365-capsule-toner",
    brand: "에스트라",
    name: "아토베리어365 캡슐토너",
    category: "cosmetics",
    defaultVolume: 300,
    unit: "ml",
    segment: "K-뷰티 토너",
    comparisonMode: "unit_value",
    sourceTargets: ["롯데·신라·신세계·현대", "올리브영·쿠팡"],
  },
  {
    id: "medicube-zero-pore-pad",
    brand: "메디큐브",
    name: "제로 모공 패드 2.0",
    category: "cosmetics",
    defaultVolume: 70,
    unit: "개",
    segment: "K-뷰티 패드",
    comparisonMode: "unit_value",
    sourceTargets: ["롯데·신라·신세계·현대", "올리브영·쿠팡"],
  },
  // ── 2026-08-30 확대 1차 ──────────────────────────────────────────
  // 롯데·현대 온라인면세점을 전수 조사해 상품 페이지를 열어 확인한 것만
  // 넣었다 (신라는 봇 차단, 신세계는 406이라 미확인 — 면세 출처는 확인된
  // 곳 기준). defaultVolume 은 국내 본품 용량이다. 면세가 점보 용량이면
  // 주석에 적고, 비교는 단위가로 한다.
  {
    // 롯데 확인, 면세 100ml vs 국내 본품 50ml (30·50·115ml 유통).
    id: "lancome-genifique-ultimate",
    brand: "랑콤",
    name: "제니피끄 얼티미트 세럼",
    category: "cosmetics",
    defaultVolume: 50,
    unit: "ml",
    segment: "럭셔리 세럼",
    comparisonMode: "same_product",
    sourceTargets: ["롯데", "랑콤 공식몰·백화점"],
  },
  {
    // 현대 확인(60ml 단품), 국내 공식몰 동일 60ml.
    id: "lamer-creme-de-la-mer",
    brand: "라메르",
    name: "크렘 드 라 메르",
    category: "cosmetics",
    defaultVolume: 60,
    unit: "ml",
    segment: "럭셔리 크림",
    comparisonMode: "same_product",
    sourceTargets: ["현대", "라메르 공식몰·백화점"],
  },
  {
    // 현대 확인(롯데는 품절), 국내 공식몰 125ml 동일.
    id: "sisley-emulsion-ecologique",
    brand: "시슬리",
    name: "에뮐씨옹 에꼴로지끄 어드밴스드 포뮬라",
    category: "cosmetics",
    defaultVolume: 125,
    unit: "ml",
    segment: "럭셔리 에멀전",
    comparisonMode: "same_product",
    sourceTargets: ["현대", "시슬리 공식몰·백화점"],
  },
  {
    // 현대 확인, 면세 125ml 점보 vs 국내 본품 50ml.
    id: "kiehls-ultra-facial-cream",
    brand: "키엘",
    name: "울트라 훼이셜 크림",
    category: "cosmetics",
    defaultVolume: 50,
    unit: "ml",
    segment: "수분 크림",
    comparisonMode: "same_product",
    sourceTargets: ["현대", "키엘 공식몰·백화점"],
  },
  {
    // 현대·롯데 확인, 국내 공식몰 50ml 동일.
    id: "whoo-bichup-essence",
    brand: "더후",
    name: "비첩 자생 에센스",
    category: "cosmetics",
    defaultVolume: 50,
    unit: "ml",
    segment: "럭셔리 에센스",
    comparisonMode: "same_product",
    sourceTargets: ["롯데·현대", "더후 공식몰·쿠팡"],
  },
  {
    // 롯데 확인, 국내 공식몰 60ml 동일.
    id: "whoo-cheongidan-cream",
    brand: "더후",
    name: "천기단 화현 래디언스크림",
    category: "cosmetics",
    defaultVolume: 60,
    unit: "ml",
    segment: "럭셔리 크림",
    comparisonMode: "same_product",
    sourceTargets: ["롯데", "더후 공식몰·쿠팡"],
  },
  {
    // 현대 확인 — 조사 시점 일시품절(리스팅 유효, 재입고 알림 노출).
    // 가격 등록은 재입고 후에만 성립한다.
    id: "sulwhasoo-first-care-essence",
    brand: "설화수",
    name: "윤조에센스 6세대",
    category: "cosmetics",
    defaultVolume: 90,
    unit: "ml",
    segment: "럭셔리 에센스",
    comparisonMode: "same_product",
    sourceTargets: ["현대", "설화수 공식몰·쿠팡"],
  },
  {
    // 롯데 확인, 면세 100ml 점보 vs 국내 주력 40ml.
    id: "avene-cicalfate-plus",
    brand: "아벤느",
    name: "시칼파트 플러스 SOS 크림",
    category: "cosmetics",
    defaultVolume: 40,
    unit: "ml",
    segment: "더모코스메틱 진정 크림",
    comparisonMode: "same_product",
    sourceTargets: ["롯데", "올리브영·쿠팡"],
  },
  {
    // 롯데 확인, 국내 200ml 동일.
    id: "biotherm-life-plankton-essence",
    brand: "비오템",
    name: "라이프 플랑크톤 온천수 에센스",
    category: "cosmetics",
    defaultVolume: 200,
    unit: "ml",
    segment: "더모코스메틱 에센스",
    comparisonMode: "same_product",
    sourceTargets: ["롯데", "비오템 공식스토어·백화점"],
  },
  {
    // 롯데 확인, 면세 100ml vs 국내 본품 75ml. 남성 스킨케어 1호.
    id: "biotherm-homme-aquapower",
    brand: "비오템 옴므",
    name: "아쿠아파워 모이스춰라이저",
    category: "cosmetics",
    defaultVolume: 75,
    unit: "ml",
    segment: "남성 수분 크림",
    comparisonMode: "same_product",
    sourceTargets: ["롯데", "비오템 공식스토어·쿠팡"],
  },
  {
    // 롯데 확인, 국내 공식몰 50ml 동일.
    id: "clarins-double-serum",
    brand: "클라랑스",
    name: "더블세럼",
    category: "cosmetics",
    defaultVolume: 50,
    unit: "ml",
    segment: "럭셔리 세럼",
    comparisonMode: "same_product",
    sourceTargets: ["롯데", "클라랑스 공식몰·백화점"],
  },
  {
    // 롯데 확인. 면세 페이지에 세부 타입(하이드레이팅/플루이드) 미표기 —
    // 가격 등록 때 타입까지 대조할 것.
    id: "lrp-anthelios-uvmune",
    brand: "라로슈포제",
    name: "안뗄리오스 UV뮨 400 SPF50+",
    category: "cosmetics",
    defaultVolume: 50,
    unit: "ml",
    segment: "선케어",
    comparisonMode: "same_product",
    sourceTargets: ["롯데", "라로슈포제 공식몰·쿠팡"],
  },
  {
    // 롯데 확인 — 조사 시점 일시품절(리스팅 유효). 국내 30ml 동일.
    id: "lrp-effaclar-serum",
    brand: "라로슈포제",
    name: "에빠끌라 울트라 컨센트레이트 세럼",
    category: "cosmetics",
    defaultVolume: 30,
    unit: "ml",
    segment: "더모코스메틱 세럼",
    comparisonMode: "same_product",
    sourceTargets: ["롯데", "라로슈포제 공식몰·쿠팡"],
  },
  {
    // 롯데 확인, 국내 공식몰 100ml 동일.
    id: "physiogel-red-soothing-cream",
    brand: "피지오겔",
    name: "레드수딩 AI 리페어 크림",
    category: "cosmetics",
    defaultVolume: 100,
    unit: "ml",
    segment: "더모코스메틱 진정 크림",
    comparisonMode: "same_product",
    sourceTargets: ["롯데", "피지오겔 공식몰·올리브영·쿠팡"],
  },
  {
    // 롯데 확인, 국내 200ml 동일.
    id: "manyo-pure-cleansing-oil",
    brand: "마녀공장",
    name: "퓨어 클렌징 오일",
    category: "cosmetics",
    defaultVolume: 200,
    unit: "ml",
    segment: "K-뷰티 클렌징",
    comparisonMode: "same_product",
    sourceTargets: ["롯데", "마녀공장 공식몰·올리브영·쿠팡"],
  },
  {
    // 롯데 확인, 국내 200ml 동일.
    id: "numbuzin-no5-toner",
    brand: "넘버즈인",
    name: "5번 글루타치온C 비타수액 에센셜토너",
    category: "cosmetics",
    defaultVolume: 200,
    unit: "ml",
    segment: "K-뷰티 토너",
    comparisonMode: "same_product",
    sourceTargets: ["롯데", "올리브영·쿠팡"],
  },
  {
    // 롯데 확인, 국내 200ml 동일.
    id: "abib-heartleaf-toner",
    brand: "아비브",
    name: "어성초 카밍 토너 스킨 부스터",
    category: "cosmetics",
    defaultVolume: 200,
    unit: "ml",
    segment: "K-뷰티 토너",
    comparisonMode: "same_product",
    sourceTargets: ["롯데", "올리브영·쿠팡"],
  },
  {
    // 롯데 확인, 국내 11g 동일.
    id: "nars-light-reflecting-powder",
    brand: "나스",
    name: "라이트 리플렉팅 세팅 파우더 루스",
    category: "cosmetics",
    defaultVolume: 11,
    unit: "g",
    segment: "베이스 메이크업",
    comparisonMode: "same_product",
    sourceTargets: ["롯데", "나스 공식몰·백화점"],
  },
  {
    // 롯데 확인, 면세 12g vs 국내 15g — 단위가 비교.
    id: "mac-studio-fix-powder",
    brand: "맥",
    name: "스튜디오 픽스 파우더 플러스 파운데이션",
    category: "cosmetics",
    defaultVolume: 15,
    unit: "g",
    segment: "베이스 메이크업",
    comparisonMode: "same_product",
    sourceTargets: ["롯데", "맥 공식몰·백화점"],
  },
  {
    // 롯데 확인, 국내 50ml 동일.
    id: "hera-uv-protector",
    brand: "헤라",
    name: "UV프로텍터 멀티디펜스 EX",
    category: "cosmetics",
    defaultVolume: 50,
    unit: "ml",
    segment: "선케어",
    comparisonMode: "same_product",
    sourceTargets: ["롯데", "헤라 공식몰·쿠팡"],
  },
  {
    // 롯데 확인(22g 대용량), 국내 14g·22g 유통 — 22g 기준.
    id: "ahc-airrich-sunstick",
    brand: "AHC",
    name: "마스터즈 에어리치 선스틱",
    category: "cosmetics",
    defaultVolume: 22,
    unit: "g",
    segment: "선케어",
    comparisonMode: "same_product",
    sourceTargets: ["롯데", "올리브영·쿠팡"],
  },
  {
    id: "balvenie-doublewood-12",
    brand: "더 발베니",
    name: "더블우드 12년",
    category: "liquor",
    defaultVolume: 700,
    unit: "ml",
    segment: "입문 싱글몰트",
    comparisonMode: "same_product",
    sourceTargets: ["롯데·신라·신세계·현대", "성인 인증 픽업몰 2곳"],
  },
  {
    id: "glenmorangie-lasanta-12",
    brand: "글렌모렌지",
    name: "라산타 12년",
    category: "liquor",
    defaultVolume: 700,
    unit: "ml",
    segment: "셰리 싱글몰트",
    comparisonMode: "same_product",
    sourceTargets: ["롯데·신라·신세계·현대", "성인 인증 픽업몰 2곳"],
  },
  {
    id: "laphroaig-10",
    brand: "라프로익",
    name: "10년",
    category: "liquor",
    defaultVolume: 700,
    unit: "ml",
    segment: "피트 싱글몰트",
    comparisonMode: "same_product",
    sourceTargets: ["롯데·신라·신세계·현대", "성인 인증 픽업몰 2곳"],
  },
  {
    id: "macallan-double-cask-12",
    brand: "맥캘란",
    name: "더블 캐스크 12년",
    category: "liquor",
    defaultVolume: 700,
    unit: "ml",
    segment: "프리미엄 싱글몰트",
    comparisonMode: "same_product",
    sourceTargets: ["롯데·신라·신세계·현대", "성인 인증 픽업몰 2곳"],
  },
  {
    id: "glenfiddich-15-solera",
    brand: "글렌피딕",
    name: "15년 솔레라",
    category: "liquor",
    defaultVolume: 700,
    unit: "ml",
    segment: "숙성 싱글몰트",
    comparisonMode: "same_product",
    sourceTargets: ["롯데·신라·신세계·현대", "성인 인증 픽업몰 2곳"],
  },
];
