import type { OfferCategory, OfferUnit } from "./offer-input";

export type PilotProduct = {
  id: string;
  brand: string;
  name: string;
  category: OfferCategory;
  defaultVolume: number;
  unit: OfferUnit;
  segment: string;
  comparisonMode: "same_product" | "unit_value";
  sourceTargets: readonly string[];
};

export const pilotProducts: readonly PilotProduct[] = [
  {
    id: "estee-lauder-anr",
    brand: "에스티 로더",
    name: "어드밴스드 나이트 리페어",
    category: "cosmetics",
    defaultVolume: 50,
    unit: "ml",
    segment: "럭셔리 세럼",
    comparisonMode: "same_product",
    sourceTargets: ["온라인 면세점", "쿠팡·국내몰"],
  },
  {
    id: "sk-ii-facial-treatment-essence",
    brand: "SK-II",
    name: "페이셜 트리트먼트 에센스",
    category: "cosmetics",
    defaultVolume: 160,
    unit: "ml",
    segment: "럭셔리 에센스",
    comparisonMode: "same_product",
    sourceTargets: ["온라인 면세점", "쿠팡·국내몰"],
  },
  {
    id: "sulwhasoo-concentrated-ginseng-cream",
    brand: "설화수",
    name: "자음생크림 클래식",
    category: "cosmetics",
    defaultVolume: 50,
    unit: "ml",
    segment: "럭셔리 크림",
    comparisonMode: "same_product",
    sourceTargets: ["온라인 면세점", "국내 공식몰"],
  },
  {
    id: "anua-heartleaf-pore-control-cleansing-oil",
    brand: "아누아",
    name: "어성초 포어 컨트롤 클렌징오일",
    category: "cosmetics",
    defaultVolume: 200,
    unit: "ml",
    segment: "K-뷰티 클렌징",
    comparisonMode: "same_product",
    sourceTargets: ["올리브영·쿠팡", "온라인 면세점"],
  },
  {
    id: "anua-heartleaf-quercetinol-cleansing-foam",
    brand: "아누아",
    name: "어성초 쿼세티놀 모공 딥 클렌징 폼",
    category: "cosmetics",
    defaultVolume: 150,
    unit: "ml",
    segment: "K-뷰티 클렌징",
    comparisonMode: "same_product",
    sourceTargets: ["올리브영·쿠팡", "온라인 면세점"],
  },
  {
    id: "torriden-dive-in-serum",
    brand: "토리든",
    name: "다이브인 저분자 히알루론산 세럼",
    category: "cosmetics",
    defaultVolume: 50,
    unit: "ml",
    segment: "K-뷰티 세럼",
    comparisonMode: "unit_value",
    sourceTargets: ["올리브영", "쿠팡·온라인 면세점"],
  },
  {
    id: "round-lab-birch-juice-sunscreen",
    brand: "라운드랩",
    name: "자작나무 수분 선크림",
    category: "cosmetics",
    defaultVolume: 50,
    unit: "ml",
    segment: "K-뷰티 선케어",
    comparisonMode: "unit_value",
    sourceTargets: ["올리브영", "쿠팡·온라인 면세점"],
  },
  {
    id: "beauty-of-joseon-relief-sun",
    brand: "조선미녀",
    name: "맑은쌀 선크림",
    category: "cosmetics",
    defaultVolume: 50,
    unit: "ml",
    segment: "K-뷰티 선케어",
    comparisonMode: "unit_value",
    sourceTargets: ["올리브영", "쿠팡·온라인 면세점"],
  },
  {
    id: "aestura-atobarrier365-capsule-toner",
    brand: "에스트라",
    name: "아토베리어365 캡슐토너",
    category: "cosmetics",
    defaultVolume: 300,
    unit: "ml",
    segment: "K-뷰티 토너",
    comparisonMode: "unit_value",
    sourceTargets: ["올리브영", "쿠팡·온라인 면세점"],
  },
  {
    id: "medicube-zero-pore-pad",
    brand: "메디큐브",
    name: "제로 모공 패드 2.0",
    category: "cosmetics",
    defaultVolume: 70,
    unit: "개",
    segment: "K-뷰티 패드",
    comparisonMode: "unit_value",
    sourceTargets: ["올리브영", "쿠팡·온라인 면세점"],
  },
  {
    id: "balvenie-doublewood-12",
    brand: "더 발베니",
    name: "더블우드 12년",
    category: "liquor",
    defaultVolume: 700,
    unit: "ml",
    segment: "입문 싱글몰트",
    comparisonMode: "same_product",
    sourceTargets: ["온라인 면세점", "성인 인증 픽업몰"],
  },
  {
    id: "glenmorangie-lasanta-12",
    brand: "글렌모렌지",
    name: "라산타 12년",
    category: "liquor",
    defaultVolume: 700,
    unit: "ml",
    segment: "셰리 싱글몰트",
    comparisonMode: "same_product",
    sourceTargets: ["온라인 면세점", "성인 인증 픽업몰"],
  },
  {
    id: "laphroaig-10",
    brand: "라프로익",
    name: "10년",
    category: "liquor",
    defaultVolume: 700,
    unit: "ml",
    segment: "피트 싱글몰트",
    comparisonMode: "same_product",
    sourceTargets: ["온라인 면세점", "성인 인증 픽업몰"],
  },
  {
    id: "macallan-double-cask-12",
    brand: "맥캘란",
    name: "더블 캐스크 12년",
    category: "liquor",
    defaultVolume: 700,
    unit: "ml",
    segment: "프리미엄 싱글몰트",
    comparisonMode: "same_product",
    sourceTargets: ["온라인 면세점", "성인 인증 픽업몰"],
  },
  {
    id: "glenfiddich-15-solera",
    brand: "글렌피딕",
    name: "15년 솔레라",
    category: "liquor",
    defaultVolume: 700,
    unit: "ml",
    segment: "숙성 싱글몰트",
    comparisonMode: "same_product",
    sourceTargets: ["온라인 면세점", "성인 인증 픽업몰"],
  },
];
