import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "next-env.d.ts",
    // `build/` holds this project's own Vite plugin and check scripts, so it is
    // deliberately not ignored here even though eslint-config-next ignores it
    // by default — that exclusion hid our own source from linting.

    // Generated by `wrangler types`; freshness is enforced by `check:types`.
    "worker-configuration.d.ts",
  ]),
]);

export default eslintConfig;
